### ISSUE TITLE
Several `NF-MDI` Icons were removed from Nerd Fonts

### ISSUE THREAD

**Issue by CodexLink** [CodexLink/chips.omp.json#12]
## Context

Recently when I was rebuilding my Fonts in [dotfiles](https://github.com/CodexLink/dotfiles/tree/latest/font) repo, I noticed that when I applied my font to my Laptop, there are several icons related to Material Design is missing.

< INSERT PHOTO HERE >

## Solution

Find a replacement.

## TODOs

- [ ] Documentation in `README.md`
- [ ] Upstream Changes in `oh-my-posh` Repository
- [ ] Update Single Width Glyph Version
- - [ ] Maintain Legacy/Fallback Build
- [ ] Update Double Width Glyph Version
- - [ ] Maintain Legacy/Fallback Build

**Comment by CodexLink** [comment]
# For Investigation
![image](https://github.com/CodexLink/chips.omp.json/assets/5953927/6217142f-1c2f-468c-9c7e-3dcec1714206)
> From https://www.nerdfonts.com/releases
